# Generated by Django 4.0.1 on 2022-01-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0002_anketa'),
    ]

    operations = [
        migrations.AddField(
            model_name='anketa',
            name='username',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
