# Generated by Django 4.0.1 on 2022-01-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0004_alter_anketa_yosh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sotib_olingan_maxsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=30)),
                ('narxi', models.IntegerField()),
                ('miqdori', models.IntegerField()),
                ('username', models.TextField()),
                ('rasm1', models.ImageField(upload_to='media')),
                ('tur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfiles.type')),
            ],
        ),
    ]
