# Generated by Django 4.0.1 on 2022-01-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0005_sotib_olingan_maxsulotlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='yosh',
            field=models.IntegerField(),
        ),
    ]
