# Generated by Django 4.0.1 on 2022-01-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfiles', '0007_remove_sotib_olingan_maxsulotlar_rasm1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sotib_olingan_maxsulotlar',
            name='tur',
            field=models.CharField(max_length=30),
        ),
    ]
